version: '3'
services:

  proxy_server:
    build: ./proxy_server
    ports:
    - "5000:5000"
    environment:
    - HOST_1=web1
    - HOST_2=web2
    - PORT=3000

  data:
    image: postgres:9.6.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    volumes:
    - "psql-data:/var/lib/postgresql/data"

  web1:
    build: ./webapp
    depends_on:
    - data
    environment:
    - DATABASE_URL=postgresql://postgres:mypassword@data:5432/postgres

  web2:
    build: ./webapp
    depends_on:
    - data
    environment:
    - DATABASE_URL=postgresql://postgres:mypassword@data:5432/postgres

volumes:
  psql-data: